/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TheA11yCta {
        /**
          * Label for the component.
         */
        "label": string;
        /**
          * Target source in case of a link.
         */
        "src"?: string;
        /**
          * Target attribute for the link.
         */
        "target"?: string;
    }
}
declare global {
    interface HTMLTheA11yCtaElement extends Components.TheA11yCta, HTMLStencilElement {
    }
    var HTMLTheA11yCtaElement: {
        prototype: HTMLTheA11yCtaElement;
        new (): HTMLTheA11yCtaElement;
    };
    interface HTMLElementTagNameMap {
        "the-a11y-cta": HTMLTheA11yCtaElement;
    }
}
declare namespace LocalJSX {
    interface TheA11yCta {
        /**
          * Label for the component.
         */
        "label"?: string;
        /**
          * Target source in case of a link.
         */
        "src"?: string;
        /**
          * Target attribute for the link.
         */
        "target"?: string;
    }
    interface IntrinsicElements {
        "the-a11y-cta": TheA11yCta;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "the-a11y-cta": LocalJSX.TheA11yCta & JSXBase.HTMLAttributes<HTMLTheA11yCtaElement>;
        }
    }
}
